# Generated by Django 2.0.6 on 2019-08-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
