# Generated by Django 2.0.6 on 2019-08-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190826_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
