# Generated by Django 2.0.6 on 2019-09-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_academic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_profile',
        ),
    ]
