# Generated by Django 2.0.6 on 2019-09-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190901_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='std',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='student',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
