# Generated by Django 2.0.6 on 2019-09-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20190908_0411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
