# Generated by Django 2.0.6 on 2019-09-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='up',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
