# Generated by Django 2.0.6 on 2019-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20190908_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField()),
                ('bio', models.IntegerField()),
                ('eng', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
        ),
    ]
